# version: '3.5'


# services:
#   postgres:
#     container_name: postgres_demo
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: super_admin
#       POSTGRES_PASSWORD: SomeSecretPassword
#       PGDATA: /data/postgres
#     volumes:
#        - postgres-db:/data/postgres
#     ports:
#       - "5432:5432"


# volumes:
#   postgres-db:
#     driver: local




version: '3'

services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      #- data:/var/lib/postgresql/data
      - ./usuario.sql:/docker-entrypoint-initdb.d/usuario.sql

  pg-admin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
volumes:
  data:
  