version: '3'

services:
  postgres:
    image: postgres
    container_name: nomeDoBanco
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      #- data:/var/lib/postgresql/data
      - ./usuario.sql:/docker-entrypoint-initdb.d/usuario.sql

  pg-admin:

    image: dpage/pgadmin4:6
    
    environment:
    
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    
    ports:
      - "5050:5050"

volumes:
  data:
  